### ISSUE TITLE
Wrong gadget address for a vmlinux ELF x86_64

### ISSUE THREAD

**Issue by XVilka** [sashs/Ropper#107]
Ropper returns invalid addresses for the gadget, compared to IDA and qemu.
See the result of qemu + gdb:
![image](https://user-images.githubusercontent.com/203261/62024823-dd12f380-b208-11e9-8418-899d7479eeea.png)
And in IDA Pro:
![image](https://user-images.githubusercontent.com/203261/62024848-eac87900-b208-11e9-844b-e229f05b7139.png)
While ropper returns this address:
![image](https://user-images.githubusercontent.com/203261/62024876-fddb4900-b208-11e9-8221-c59fcf50ce09.png)

See the 0x200000 address difference. Also see that LOAD0 segment starts from 0x200000 as well, 

[vmlinux.zip](https://github.com/sashs/Ropper/files/3440426/vmlinux.zip)

**Comment by sashs** [comment]
Oh, thank you. I will check that.

**Comment by sashs** [comment]
I've found to problem. The image base calculation is wrong, at least for vmlinux. I need to think about how to solve it.

**Comment by sashs** [comment]
I pushed a fix. It should work now.

**Comment by sashs** [comment]
I will close this issue.
