### ISSUE TITLE
See badbytes in console

### ISSUE THREAD

**Issue by disconnect3d** [sashs/Ropper#108]
Hey,

It would be nice to have a feature to see which `badbytes` are set in the interactive console.

At first I thought that just `badbytes` will do it, but it cleared them instead :P.

**Comment by sashs** [comment]
Hi,

this is possible. You can use the command `settings` to show all settings, including badbytes. If you want to change the settings you can use the command `settings <name of setting> <value>`.

**Comment by disconnect3d** [comment]
Hey,

Good to know, thanks :).
