### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by KittyTechnoProgrammer** [sashs/Ropper#115]
Its me again. I see what you were going for here. I assume you were trying to print out some information. However now it gives a TypeError 

P.S. Thx for replying so fast, and updating.

[INFO] Load gadgets from cache
[LOAD] loading... 100%
[LOAD] removing double gadgets... 100%

[INFO] Ropchain Generator for VirtualProtect:

[INFO] eax 0x90909090
ecx old protection (writable addr)
edx 0x40 (RWE)
ebx size
esp address
ebp return address (jmp esp)
esi pointer to VirtualProtect
edi ret (rop nop)

Traceback (most recent call last):
  File "/opt/Ropper/ropper/console.py", line 360, in __generateChain
    chain = self.__rs.createRopChain(generator, str(self.currentFile.arch) ,options)
  File "/opt/Ropper/ropper/service.py", line 775, in createRopChain
    return generator.create(options)
  File "/opt/Ropper/ropper/ropchain/arch/ropchainx86.py", line 958, in create
    self._printMessage('Try to create gadget to fill esi with content of IAT address: 0x%x' % (address + image_base))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

[ERROR] Please report this error on https://github.com/sashs/ropper
[ERROR] Traceback (most recent call last):
  File "/opt/Ropper/ropper/console.py", line 62, in cmd
    func(self, text)
  File "/opt/Ropper/ropper/console.py", line 499, in __handleOptions
    self.__generateChain(options.chain)
  File "/opt/Ropper/ropper/console.py", line 377, in __generateChain
    raise e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by sashs** [comment]
Hi,

Can you provide the binary, please? It should not reach that point if address or image_base is None.
Therefore, I need a possibility to reproduce this issue.

**Comment by KittyTechnoProgrammer** [comment]
Sorry for taking so long was at a party. The binary is here : 
[FTPServer.exe.zip](https://github.com/sashs/Ropper/files/3719441/FTPServer.exe.zip)

Hope this helps.

**Comment by KittyTechnoProgrammer** [comment]
This is normaly a pretty easy ctf, but wanted to try with DEP.
