### ISSUE TITLE
Badbytes doesn't check the ImageBase provided.

### ISSUE THREAD

**Issue by lionaneesh** [sashs/Ropper#117]
The address of image base is not considered while filtering bad bytes. I will try to make a change for this.

```

$ ropper -f libc-2.15.so -I  0x5555e000 --badbytes "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfe"
[INFO] Load gadgets from cache
[LOAD] loading... 100%
[LOAD] filtering badbytes... 100%



Gadgets
=======



0 gadgets found

```

A gadget I found manually:

```(gdb) x/5i 0x555f3555                                                                                                 
   0x555f3555:  pop    %edx
   0x555f3556:  xor    %eax,%eax
   0x555f3558:  pop    %edi
   0x555f3559:  ret    
```

Ropper shows wrong output here.

**Comment by sashs** [comment]
Hi, 

why do you think this is a wrong output. Ropper should not show that gadget because of 0x5f which is filtered by the badbytes setting.

**Comment by sashs** [comment]
Oh wait, I was wrong

**Comment by sashs** [comment]
Could you provide your libc

**Comment by lionaneesh** [comment]
Yeah sure. Just a second.  https://filetransfer.io/data-package/UUF9RiEr

**Comment by lionaneesh** [comment]
Is it fine if I try to make the change? I am trying to figure out whats wrong in lines[0][0] holding so huge values in my case. (inside Gadget, addressesContainsBytes)

**Comment by sashs** [comment]
I found the problem.

**Comment by lionaneesh** [comment]
What is it?

**Comment by sashs** [comment]
The newly set image base is used during the searching process and used for the offset calculation.
I fixed it and I will push a fix later today.

If you want to look for gadgets now, clear the cache with `ropper --clear-cache` and start ropper once without setting the image base. After that it works since the gadgets are loaded from the cache.

**Comment by lionaneesh** [comment]
Hey did you push the change for this?

**Comment by sashs** [comment]
Yes, today.
