### ISSUE TITLE
Bad bytes does not work

### ISSUE THREAD

**Issue by jstaursky** [sashs/Ropper#121]
I need to filter out `int 0x80` (i.e, sys_call insn) from the gadgets returned by ropper
![EXAMPLE_ROPPER_page1](https://user-images.githubusercontent.com/25406664/70852041-b9281580-1e6a-11ea-9a85-4fa9ee26a685.png)
 but adding `-b 'cd80'` doesn't seem to have any affect.

**Comment by sashs** [comment]
Hello,

the bad bytes option do work, however you have not understand how it works ;)
Since a ropchain consists of the addresses, the badbytes option filters addresses and not intructions ;)

Due to your question I think such a filter option makes sense.

**Comment by jstaursky** [comment]
Ah well bummer. Thanks anyway.
