### ISSUE TITLE
can't pipe ropper output to less

### ISSUE THREAD

**Issue by AravGarg** [sashs/Ropper#134]
Piping the output of ropper to less doesn't seem to work.
For example: `ropper --file ./vmlinux --detailed --all --search "pop rdi" | less`

**Comment by sashs** [comment]
Hi, what exactly does not work?
However, since the output is colored, you should use the option --nocolor

**Comment by AravGarg** [comment]
<img width="1680" alt="Screenshot 2020-11-23 at 11 04 40" src="https://user-images.githubusercontent.com/39301993/99936099-c1c3e400-2d7b-11eb-961b-5fecbe77aacb.png">

Here's the output!
Worked fine with -nocolor thanks!!!
