### ISSUE TITLE
Enhancement: Excessive help message

### ISSUE THREAD

**Issue by davidhcefx** [sashs/Ropper#137]
## Description

Every time I typed `ropper --help`, *ropper* would spit out a **four-page help message**, which is overwhelming to me. In most scenarios, what I really want to find is just the correct `keywords` in order to use *ropper*. For instance, `--file` and `--search` are the two keywords I used the most.

![help-msg](https://user-images.githubusercontent.com/23246033/103140858-bff89200-4726-11eb-821c-dc86cdbe39bf.png)

Besides, as shown in the image above, each example command was displayed as the **FULL PATH** of *ropper*, which made the lines redundant and ugly:

```
C:\Users\user\Local\Programs\Python\Python38\Scripts\ropper --file /bin/ls --search "mov e?x"
```

## Suggestion

Here are some suggestions I came out with:
- In each example command, use plain `ropper` instead of the FULL PATH.
- Only show brief help messages. Put detailed description into another option, for example `--help-detail`.
- Or perhaps, put the examples into another option instead, for example `--help-examples`.

**Comment by sashs** [comment]
Hey. 
I removed the examples from the help page and added a new command `--help-examples`.
