### ISSUE TITLE
Build ROP chain for X86_64 Problem

### ISSUE THREAD

**Issue by pfsun** [sashs/Ropper#15]
Ropper is really great tool. Now I try to use it to build ROP chain for x86_64 binary. I always meet one error: "[ERROR] generator execve is for arch ArchitectureX86_64 not available". I also check /ropper/ropchian/arch, there is only x86. So it is only support to build rop chain for x86 binary, right?
Thanks.
Pengfei

**Comment by sashs** [comment]
Hey. Thanks, 

Yes that is right, at the moment only rop chain generators for x86 are available. 

I will change this ERROR message with a  INFO message and I will change the text a little bit, then it will be clearer. :)

regards
Sascha
