### ISSUE TITLE
multiple test regressions in 1.8.0

### ISSUE THREAD

**Issue by anthraxx** [sashs/Ropper#18]
When running the test suite (with python3) I get the following errors, which make it impossible to release the 1.8.0 version: OverflowError: cannot fit 'int' into an index-sized integer

I have created a bug report for the affected library: https://github.com/sashs/filebytes/issues/2

PS: the tests were running on i686 (32bit) because of the packaging process

**Comment by anthraxx** [comment]
new version of python-filebytes fixed the issue, thx :+1:

**Comment by sashs** [comment]
Thank you for packing it for arch. ;-)

**Comment by anthraxx** [comment]
of cause, always a pleasure with such fast upstream problem handling :smile:
