### ISSUE TITLE
pyproject.toml compatibility with future python

### ISSUE THREAD

**Issue by anthraxx** [sashs/Ropper#181]
It would be great if this project can implement future pyproject.toml declaration requirement as otherwise future python versions won't be able to be used with this project. It's always good to be ready before the deadline hits :cat: 

https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

thanks! :)

**Comment by sashs** [comment]
Hey. 
Thank you. :)
I will look at that as soon as I have fixed the pyvex issue.
