### ISSUE TITLE
Installation only possible if capstone gets compiled on the system

### ISSUE THREAD

**Issue by mitp0sh** [sashs/Ropper#24]
Hey Sasha, 

  first thanks for the great tool. I was introduced to it by Saumil while doing a training he gave.

I would like to use the tool on windows as well, not only on my linux machines. I tried to install it using the small guide you show in your README.md.

I have the requirement that I don't want to install cygwin to compile Capstone because I guess that is not necessary, right ? There is precompiled binary windows package which can be installed as following:

`pip install capstone-windows`

Basically I thought that you mind accept this as well but the installer unfortunately failed. See the error message here:

`Installed c:\python27\lib\site-packages\ropper-1.9.2-py2.7.egg
Processing dependencies for ropper==1.9.2
Searching for capstone
Reading https://pypi.python.org/simple/capstone/
Best match: capstone 3.0.4
Downloading https://pypi.python.org/packages/e7/29/e9ad2a12c38f19e9ca8aff05122e5b9e271da6ecbfb6c4e20aee381b49ff/capstone-3.0.4.tar.gz#md5=3437fa632c89531a7d800a3f8c04fbe3
Processing capstone-3.0.4.tar.gz
Writing c:\users\xxx\appdata\local\temp\easy_install-wou9zr\capstone-3.0.4\setup.cfg
Running capstone-3.0.4\setup.py -q bdist_egg --dist-dir c:\users\xxx\appdata\local\temp\easy_install-wou9zr\capstone-3.0.4\egg-dist-tmp-qch518
'cmake' is not recognized as an internal or external command,
operable program or batch file.
'nmake' is not recognized as an internal or external command,
operable program or batch file.
error: Setup script exited with error: can't copy 'src\build\capstone.dll': doesn't exist or not a regular file`

I can see that nmake is missing which makes sense, I don't have it installed. But again I don't want to compile Capstone from scratch.

Can you eventually modify the setup in a way that it accepts the capstone-windows distribution as well ? Or maybe I'm missing something basic here !?

Thank you for your efforts!

mitp0sh of [PDX]

**Comment by sashs** [comment]
Hey,

I will look at this.


Regards
Sascha

**Comment by sashs** [comment]
Hey, 

it should work now.


Regards
Sascha
