### ISSUE TITLE
some gadgets may not be found

### ISSUE THREAD

**Issue by anthraxx** [sashs/Ropper#26]
Hi, I have noticed that some gadgets may not be shown under certain circumstances.

an example would be provided by this simple program:
```c
#include <unistd.h>
#include <sys/types.h>

static int64_t test()
{
	return -1;
}

int main()
{
	return test();
}
```

This should have the following gadget (depending on representation the content could also be a -1):
```asm
mov rax,0xffffffffffffffff
pop rbp
ret
```

the output of objdump:
```asm
objdump -d ./test -Mintel|grep ret -B3
--
  4004a7:	48 89 e5             	mov    rbp,rsp
  4004aa:	48 c7 c0 ff ff ff ff 	mov    rax,0xffffffffffffffff
  4004b1:	5d                   	pop    rbp
  4004b2:	c3                   	ret    
```

search via ropper (not its also not available via listing all gadgets with the `gadgets` command:
```
(ropper) file ./test
[INFO] File loaded.

(ropper) badbytes
[INFO] badbytes cleared
[INFO] Filter gadgets of all opened files
[INFO] Filtering gadgets finished
[INFO] Gadgets have to be reloaded

(ropper) load
[INFO] Loading gadgets for section: PHDR
[LOAD] loading... 100%
[INFO] Loading gadgets for section: LOAD
[LOAD] loading... 100%
[INFO] deleting double gadgets...
[LOAD] clearing up... 100%
[INFO] gadgets loaded.

(ropper) search mov rax
[INFO] Search in gadgets of file './test'
[INFO] Searching for gadgets: mov rax
[LOAD] searching gadgets... 100%

Gadgets
=======
0 gadgets found
```

**Comment by sashs** [comment]
Fixed!
(ropper) search %mov rax
[INFO] Searching for gadgets: %mov rax

[INFO] File: testapp
0x00000000004004a8: mov ebp, esp; mov rax, -1; pop rbp; ret; 
0x00000000004004aa: mov rax, -1; pop rbp; ret; 
0x00000000004004a7: mov rbp, rsp; mov rax, -1; pop rbp; ret; 
0x00000000004004a6: push rbp; mov rbp, rsp; mov rax, -1; pop rbp; ret; 

You will find it today in dev branch.

**Comment by anthraxx** [comment]
thx a lot, very fast :+1:

**Comment by sashs** [comment]
Welcome. :)
