### ISSUE TITLE
multiple file opening at once

### ISSUE THREAD

**Issue by iz0n** [sashs/Ropper#31]
Hi,

Great project !

Is it possible to implement a feature that allows multiple file opening ?
- multiple files in one line
- usage of wildcards.

Thank you :)

**Comment by sashs** [comment]
Hi,

thanks. 
Yes, I have in a dev version the possibility to give a list of files to --file, but this is not pushed to github at the moment. But in future versions this will be possible. 

cheers
Sascha

**Comment by sashs** [comment]
Hey. 

You can provide a list of file, when you start ropper.
ropper --file file1 file2 file3
