### ISSUE TITLE
ropchain virtualprotect: local variable 'size' referenced before assignment

### ISSUE THREAD

**Issue by iz0n** [sashs/Ropper#37]
Hi,
A small bug in ropchain feature :)
Output message:
[INFO] Ropchain Generator for VirtualProtect:

[INFO] eax 0x90909090
ecx old protection (writable addr)
edx 0x40 (RWE)
ebx size
esp address
ebp return address (jmp esp)
esi pointer to VirtualProtect
edi ret (rop nop)

[ERROR] local variable 'size' referenced before assignment
[ERROR] Please report this error on https://github.com/sashs/ropper

Thank you,

**Comment by sashs** [comment]
Fixed. Look at the dev branch. 
Size is not needed.
