### ISSUE TITLE
file feature speed enhancement

### ISSUE THREAD

**Issue by iz0n** [sashs/Ropper#38]
Hi,
For big projects (many files to load), it is better to define all files then load then in one shot.
I think, i should be better if it is possible to enable/disable automating gadgets loading/calculation when "opening a new file" with "file" command :)

Thank you,

**Comment by sashs** [comment]
Hey, 

you can use --no-load when you start ropper, then it doesn't load the the gadgets automatically. 

cheers
Sascha
