### ISSUE TITLE
colors disabled automatically after ropchain error

### ISSUE THREAD

**Issue by iz0n** [sashs/Ropper#39]
Hi,
When trying the ropchain module, if it fails, the errors got disabled :-)
(MFC71u.dll/PE/x86)> color on
=> colors enabled
(MFC71u.dll/PE/x86)> ropchain virtualprotect address=0xDEADBEEF,size=0x1000
[ERROR] too many values to unpack
[ERROR] Please report this error on https://github.com/sashs/ropper
=> colors are disabled here

Thank you,

**Comment by sashs** [comment]
Fixed. Look at dev branch.
