### ISSUE TITLE
add option for ptr in execve

### ISSUE THREAD

**Issue by yoava333** [sashs/Ropper#49]
I'm using ropper and it's a really useful tool, but most of the time when trying to generate the execve chain it fail on finding write-what-where gadget. I've looked at the code and it seems that it only needs it for writing binary path to memory. Most of the time when it ropper fails I can load a string to known memory location or in the case of "/bin/sh" it's sometime just found as data in the binary.

I suggest adding a ```--chain "execve cmd_addr=0xdeadbabe"``` to ropper.
What do you think?

**Comment by sashs** [comment]
Hey, 
yes that sounds like a good idea. I will implement that.

**Comment by sashs** [comment]
Hey, 

you have now the option to set an two addresses. 
`--chain "execve address=0xdeadbabe nulladdress=0x42424242"
`
address = address to the command
nulladdress = address to null bytes.

If you don't set one of those arguments, ropper tries to create a chain that write the commend in the memory, if a writewhatwhere gadget cannot be found, ropper creates a chain in that you can set an address.
