### ISSUE TITLE
Getting print format error on rop chain generation

### ISSUE THREAD

**Issue by Roguebantha** [sashs/Ropper#50]
Running:
ropper --file `which nc` --chain execve

ends with:
...
[*] Try permuation 23 / 24

[*] Try permuation 24 / 24

[INFO] 

[INFO] Cannot create chain which fills all registers

[INFO] 

[INFO] Look for syscall gadget

[INFO] No syscall gadget found!

[INFO] Look for syscall opcode
[ERROR] %x format: a number is required, not str
[ERROR] Please report this error on https://github.com/sashs/ropper

So I'm reporting it ;)

**Comment by sashs** [comment]
Thanks for reporting it. ;) Could you tell me which file you loaded? Is that netcat?

**Comment by Roguebantha** [comment]
Yes netcat is what broke it, but I've discovered nano broke it too.

**Comment by Roguebantha** [comment]
I loaded netcat in using which to resolve the filename, which is why the formatting in github has gone all wonky.

**Comment by sashs** [comment]
Ok. Thx. I will check that!

**Comment by sashs** [comment]
Hey, this issue is fixed. 
Please look at the dev branch.
