### ISSUE TITLE
Data section's address is not calculated properly

### ISSUE THREAD

**Issue by gadol21** [sashs/Ropper#52]
I have an executable, on which i generated an execve rop chain using ropper, but it caused a segfault.
I debugged that segfault for a bit, and got to the conclusion ropper tried to write "/bin/sh" to a place
it thought was the data section, but really isn't. I think the faulty line is line 626 in ropchainx86_64.py:
```python
chain_tmp += self._createCommand(cmd,section.offset+0x1000)[0]
```
section.offset is used, and according to my understanding, this is the section's sh_offset member. but upon
some docs, it apears this field is an offset from the beginning of the file, and not an rva in memory!
i confirmed this using:
readelf -S pass_protected
which returned:
[Nr] Name              Type             Address           Offset
....
[24] .data             PROGBITS         00000000006c1060  000c1060

and the image base is actually 0x400000 (compiled without PIE), not 0x600000 (confirms that
the offset is not really the rva).
The segfault message from dmesg said that the segfault occured while trying to write to 0x4c2060,
which explains that perfectly (that is the section's offset + 0x1000, as calculated by ropper), while the
data section really begins at 0x6c1060.
Added the file whose data section address is not calculated properly.
[pass_protected.zip](https://github.com/sashs/Ropper/files/1219893/pass_protected.zip)

**Comment by gadol21** [comment]
Note:
A possible fix is to replace the given line (and similar lines in the same function) with this one:
```python
chain_tmp += self._createCommand(cmd,section.virtualAddress-Gadget.IMAGE_BASES[self._binaries[0].fileName]+0x1000)[0]
```
Its ugly, but makes the calculation correct

**Comment by sashs** [comment]
Hey,
sorry for the late reply, I will check that this week.

**Comment by sashs** [comment]
Again sorry for the delay. :)
The Bug should be fixed now.
