### ISSUE TITLE
Imagebase ignored when called from command line

### ISSUE THREAD

**Issue by evisneffos** [sashs/Ropper#56]
Thanks for providing this great tool.
I just observed a difference in the program's behaviour when being called from the command line rather than the console. The provided image base argument (-I <imagebase) seems to be ignored, whereas for the console it works as expected.

ropper -f ./libc-2.15.so -I 0x5555e000 

Gadgets
=======

0x0017cbd5: aad 0; add byte ptr [eax - 0xd], bh; out dx, eax; call
 dword ptr [eax]; 
0x000b9132: aad 0; add byte ptr [eax], al; call dword ptr gs:[0x10]; 
0x000eca1f: aad 0; add byte ptr [eax], al; call eax; 
0x000b915d: aad 0; add byte ptr [eax], al; ror eax, 9; xor  eax, dword ptr gs:[0x18]; mov dword ptr [esp], edx; call eax; 
0x00168b55: aad 0; add byte ptr [edx + edx*8], al; out dx, al; jmp  esp; 
0x0017c751: aad 0; add byte ptr [esp + edx*8], bl; out dx, eax; call dword ptr [edi + 2]; 
0x00003696: aad 0x21; lea esi, dword ptr [edx]; wait; mov word ptr [edx - 0x4a], 
dr1; sbb eax, dword ptr [0x572808a8]; call dword ptr [esi + 0x6f]; 
0x0006952f: aad 0x29; int 0x29; ret 0xe75;

**Comment by sashs** [comment]
Thx, I will check that .

**Comment by sashs** [comment]
Hi, 

which version of ropper do you use?


cheers
Sascha

**Comment by evisneffos** [comment]
The newest version available with pip, 1.11.3

**Comment by sashs** [comment]
mh, it is working for me.

**Comment by evisneffos** [comment]
Oops, the pip upgrade affected another user, I was still running 1.11.2.
So the error appears only in 1.11.2 and seems to be fixed in 1.11.3.
Thanks and sorry! Another reason for me to directly use the Github repo rather than pip.
