### ISSUE TITLE
BND prefix not supported and therefore missing gadgets

### ISSUE THREAD

**Issue by soffensive** [sashs/Ropper#57]
I am using ropper 1.11.3 and noticed the following when comparing it to ROPgadget:

ropper does not seem to find gadgets / instructions that utilize the BND prefix. For instance, in libc-2.15.so, the following gadget will not be found:

`0x00186042 : pop ebx ; jmp dword ptr [edx]`

In fact, this gadget corresponds to these two assembly instructions:
```
pop    ebx
bnd jmp DWORD PTR [edx]
```

I guess it is due to the bnd prefix, but this has yet to be confirmed.

**Comment by sashs** [comment]
I will check that

**Comment by sashs** [comment]
BND prefix is not supported
