### ISSUE TITLE
Fail to load ImageBase for relative path files

### ISSUE THREAD

**Issue by pietroborrello** [sashs/Ropper#64]
If a file is loaded in ropper with a relative path (i.e. "../test/a.out") the base address of all gadgets is wrong.
To reproduce 
```
from ropper import RopperService
rs = RopperService()
rs.addFile("../test/a.out")
rs.loadGadgetsFor(name="../test/a.out")
ropper_gadgets = rs.getFileFor(name="../test/a.out").gadgets
g = ropper_gadgets[0]
print g.imageBase
```
It results in 0

This is due to the fact that g.imageBase is calling 
```
@property
    def imageBase(self):
        return Gadget.IMAGE_BASES.get(self._fileName,0)
```

and Gadget.IMAGE_BASES is set as 
```
{'../test/a.out': 134512640L}
```
while self._fileName is set to "a.out"

**Comment by sashs** [comment]
Thank you. That is an interesting issue.

**Comment by pietroborrello** [comment]
I think this is due to the way ropper cache is initialized: in ```loadGadgetsFor()``` the call to ```f.allGadgets = self.__loadCache(f)```is performed. 

In is turn it calls ```__getCacheFileName(self, file):``` that takes the last part of the filename with ```getFileNameFromPath(file.name)``` to load searched gadgets. 
If the file was previously analyzed with a different path the field ```f.loader.imageBase```is now different, and the dictionary lookup will fail.

**Comment by sashs** [comment]
Should be fixed. Filename is not used anymore, a checksum is used instead.
