### ISSUE TITLE
Gadget with multiple pops is incorrectly categorized

### ISSUE THREAD

**Issue by baltazarortiz** [sashs/Ropper#67]
Given the instructions `pop rax; pop rdx; pop rbx; ret; `, the Gadget object categorizes it as `(LOAD_REG, 3, {'dst': 'rax'})`. 

However, this misses the `rdx` and `rbx` destinations, so the gadget will be incorrectly used in chains by the ropchain `_createDependenceChain` function if the chain is not supposed to have `rdx` or `rbx` in it.

Working on a fix in gadget.py's `category` function, but not super familiar with the codebase so I'm less clear on the best approach for this one.

**Comment by baltazarortiz** [comment]
Another example - the gadget `adc al, 0; add byte ptr [rax], al; add rsp, 0x90; xor eax, eax; pop rbx; ret;` is categorized as `(LOAD_REG, 5, {'dst': 'rbx'})`.

This misses the fact that `rsp` is changed and `eax` is zeroed out.

**Comment by sashs** [comment]
Hi, 

regarding the pop gadget, this is right. Currently only the first instruction is used to build rop chains, all other instructions are ignored. However, if another instruction uses a register that is filled before, the gadget will not be used. It does not matter if it is a write access or a read access. It is a dump algorithm to create chains. There is a lot of space for improvements. :)

**Comment by sashs** [comment]
Regarding the second gadget, this is interesting. I have to check why this is categorized as a LOAD_REG gadget.

**Comment by baltazarortiz** [comment]
Re: first gadget, where is that check being made? I opened this issue because I was getting an execve chain that ended like this:

```
...
rop += rebase_0(0x0000000000043126) # 0x0000000000443126: pop rdx; ret; 
rop += rebase_0(0x00000000002cc088)
rop += rebase_0(0x0000000000078ec6) # 0x0000000000478ec6: pop rax; pop rdx; pop rbx; ret; 
rop += p(0xdeadbeefdeadbeef)
rop += p(0xdeadbeefdeadbeef)
rop += p(0x000000000000003b)
rop += rebase_0(0x0000000000067af5) # 0x0000000000467af5: syscall; ret; 
print rop
[INFO] rop chain generated!
```

The second to last gadget with the 3 pops is overwriting the value written by the previous `pop rdx` gadget. This is the kind of conflict that should be prevented by the check you are mentioning correct? If not, I'll keep looking into fixes.

Re: second gadget, let me rerun with a clean copy to make sure it wasn't miscategorized by some changes I've made. I'll edit soon.

**Comment by sashs** [comment]
The most checks are done in the function _find function. The check i mentioned is _isModifiedOrDereferencedAccess.

**Comment by baltazarortiz** [comment]
Thanks - that one definitely isn't firing for the above example. I'll try to figure out why. I think I have a fix almost done pending some testing, so we can take a look at a pull request soon to make sure it's actually using the existing infrastructure intelligently.
