### ISSUE TITLE
Error on generating execve ropchain

### ISSUE THREAD

**Issue by adi1998** [sashs/Ropper#77]
I am getting error on running `ropper -f bin --chain execve`

The binary is static x86 32-bit 

[ERROR] Please report this error on https://github.com/sashs/ropper
[ERROR] Traceback (most recent call last):
  File "/home/aditya/ropper/ropper/console.py", line 53, in cmd
    func(self, text)
  File "/home/aditya/ropper/ropper/console.py", line 488, in __handleOptions
    self.__generateChain(options.chain)
  File "/home/aditya/ropper/ropper/console.py", line 365, in __generateChain
    raise e
NameError: global name 'regs' is not defined

**Comment by adi1998** [comment]
In particular i think commit 4a3ab26900262a2d8582f6e954a19a20d2ff9200 is causing many issues

**Comment by eternaleclipse** [comment]
@sashs This fixes it but the ```_printRopInstruction``` function fails further down the road.
```value_first``` is referenced before assignment (it's defined in an ```if``` clause),  and ```value``` is undefined.

I fixed these, tested with a statically compiled x86 binary and submitted a PR to dev branch. Cheers 🥂

**Comment by sashs** [comment]
@eternaleclipse Thank you!

Yes, you are right. I am currently to extend the current test cases.
