### ISSUE TITLE
Use of __import__

### ISSUE THREAD

**Issue by eternaleclipse** [sashs/Ropper#80]
https://github.com/sashs/Ropper/blob/7c68d285b0a04a82ba85705b7476a07f0d754e48/Ropper.py#L24

From ```__import__```'s help:
```
    Import a module. Because this function is meant for use by the Python
    interpreter and not for general use it is better to use
    importlib.import_module() to programmatically import a module.
```

Besides, importing with a string could cause problems with static code analysis tools and IDEs so it's usually a good idea to avoid them when possible.

Why not just ```import ropper```?

**Comment by sashs** [comment]
I wrote this several years ago, I do not know why I used that. :)
