### ISSUE TITLE
[ERROR] ArchitectureX86_64 does not have support for mprotect=0x00400000:0x400000 chain generation at the moment. Its a future feature.

### ISSUE THREAD

**Issue by reijin90** [sashs/Ropper#89]
Hi!

I tried to run ropper against a x86_64 binary. According to your documentation and previous usage against a different binary, this should work however. Any idea why I receive that error message now?
The command to run was like this:
`python3 ./Ropper.py --file ~/my/file --chain mprotect=0x00400000:0x400000`

**Comment by sashs** [comment]
Hi,

yes, I know it. :)
The arguments are different now. 
```
ropper -f /lmy/file --chain "mprotect address=0x00400000 size=0x400000"
```

**Comment by reijin90** [comment]
Ah! you beat me to a few seconds! Just wanted to clarify that I found it ;)
